media:
  input: public/images
  output: /images
components:
 bio-text:
   label: Homepage Biography Text
   type: rich-text
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, description, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Creation date, type: date }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: tours
    label: Tours
    type: collection
    path: src/content/tours
    view:
      fields: [ title, description, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Creation date, type: date }
      - { name: body, label: Body, type: rich-text }
  - name: home
    label: Homepage Bio
    type: file
    path: src/components/Homepage.md
    fields:
      - { name: body, label: Homepage Bio, type: rich-text}
